# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: promptnet/v1/prompt.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'promptnet/v1/prompt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19promptnet/v1/prompt.proto\x12\x0cpromptnet.v1\"$\n\x10GetPromptRequest\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\"z\n\x11GetPromptResponse\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1a\n\x08template\x18\x02 \x01(\tR\x08template\x12\x14\n\x05slots\x18\x03 \x03(\tR\x05slots\x12!\n\x0cversion_hash\x18\x04 \x01(\tR\x0bversionHash2]\n\rPromptService\x12L\n\tGetPrompt\x12\x1e.promptnet.v1.GetPromptRequest\x1a\x1f.promptnet.v1.GetPromptResponseB(Z&promptnet/gen/promptnet/v1;promptnetv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'promptnet.v1.prompt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&promptnet/gen/promptnet/v1;promptnetv1'
  _globals['_GETPROMPTREQUEST']._serialized_start=43
  _globals['_GETPROMPTREQUEST']._serialized_end=79
  _globals['_GETPROMPTRESPONSE']._serialized_start=81
  _globals['_GETPROMPTRESPONSE']._serialized_end=203
  _globals['_PROMPTSERVICE']._serialized_start=205
  _globals['_PROMPTSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
